{% set name = "periodiq" %}
{% set version = "0.13.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: ecd83d7614bb9e019aa2718b63c4ffe0a6c77fa0d49f33fd90c309982ddcf7cb

build:
  noarch: python
  number: 0
  script: "{{ PYTHON }} -m pip install . -vv"
  entry_points:
    - periodiq = periodiq:entrypoint

requirements:
  host:
    - python >=3.5
    - pip
    - poetry
  run:
    - python >=3.5
    - dramatiq
    - pendulum

test:
  imports:
    - periodiq
  commands:
    - periodiq -h

about:
  home: https://pypi.org/project/periodiq/
  license: LGPL-3.0-or-later
  license_family: LGPL
  license_file: LICENSE
  summary: 'Simple Scheduler for Dramatiq Task Queue'
  dev_url: https://gitlab.com/bersace/periodiq

extra:
  recipe-maintainers:
    - mcs07
