schema_version: 1

context:
  name: periodiq
  version: "0.14.0"

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/${{ name[0] }}/${{ name }}/periodiq-${{ version }}.tar.gz
  sha256: 88a61d4b5872b24c4cfdd70c0885952673bb6f748a29301b9aa08cb87f5d23a7

build:
  number: 0
  noarch: python
  script: ${{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  python:
    entry_points:
      - periodiq = periodiq:entrypoint

requirements:
  host:
    - python ${{ python_min }}.*
    - poetry >=0.12
    - pip
  run:
    - python >=${{ python_min }}
    - dramatiq >=1.5.0,<2.0.0
    - pendulum >=2.0,<4
    # package still uses pkg_resources, which is deprecated in setuptools though
    - setuptools <81

tests:
  - python:
      imports:
        - periodiq
      pip_check: true
      python_version: ${{ python_min }}.*
  - requirements:
      run:
        - python ${{ python_min }}.*
    script:
      - periodiq --help

about:
  homepage: https://gitlab.com/bersace/periodiq/
  summary: Simple Scheduler for Dramatiq Task Queue
  license: LGPL-3.0-or-later
  license_file:
    - COPYING.LESSER

extra:
  recipe-maintainers:
    - thewchan
    - mcs07
